# Generated by Django 3.2.9 on 2021-11-12 12:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('file', models.ImageField(default='/placeholder-home-tile.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAboutTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField()),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HomeAboutTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('file', models.ImageField(default='/placeholder-home-tile.png', upload_to='')),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('file', models.ImageField(default='/placeholder-home-slide.png', upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField()),
                ('responsible_fullname', models.CharField(max_length=60)),
                ('responsible_image', models.ImageField(default='/responsible-image-placeholder.png', upload_to='')),
                ('department_image', models.ImageField(default='/department-image-placeholder.png', upload_to='')),
                ('responsible_resume_eduction_degree', models.CharField(default=' ', max_length=60)),
                ('responsible_resume_eduction_field', models.CharField(default=' ', max_length=60)),
                ('responsible_resume_eduction_university', models.CharField(default=' ', max_length=60)),
                ('responsible_resume_eduction_date', models.CharField(default=' ', max_length=60)),
                ('responsible_resume_experience', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProjectExecutionSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProjectMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProjectPerspective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('file', models.ImageField(default='/social-network-placeholder.png', upload_to='')),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('place', models.CharField(max_length=60)),
                ('employer', models.CharField(max_length=60)),
                ('consultant', models.CharField(max_length=60)),
                ('duration', models.CharField(max_length=60)),
                ('ahjam', models.CharField(max_length=60)),
                ('start_time', models.DateField()),
                ('image_big', models.ImageField(upload_to='')),
                ('image_small', models.ImageField(upload_to='')),
                ('image_page', models.ImageField(upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comidt.servicesdepartment')),
                ('execution_step', models.ManyToManyField(to='comidt.ServicesProjectExecutionSteps')),
                ('map', models.ManyToManyField(to='comidt.ServicesProjectMap')),
                ('perspective', models.ManyToManyField(to='comidt.ServicesProjectPerspective')),
            ],
        ),
        migrations.AddField(
            model_name='servicesdepartment',
            name='social_network',
            field=models.ManyToManyField(to='comidt.ServicesSocialNetwork'),
        ),
    ]
